services:
  frontend:
    build: ./frontend
    ports:
      - 5173:5173
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - 8000:8000
    environment:
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - db
      - ollama
  db:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongo_volume:/data/db

  ollama:
    image: ollama/ollama
    ports:
      - 11435:11434
    volumes:
      - ollama_volume:/data
volumes:
  mongo_volume:
  ollama_volume: