services:
  frontend:
    build: ./frontend
    ports:
      - 5173:5173
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongo_volume:/data/db

volumes:
  mongo_volume:
  ollama_volume:
